### PR TITLE
Fixed issue with filter of undefined when using an <input type="file">

### LINKED ISSUE #164: Everything working fine, but this error message: ... what does it mean?
`error_handler.js:50 EXCEPTION: _this.files.filter is not a function
ErrorHandler.handleError @ error_handler.js:50
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:55 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:55
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:56 TypeError: _this.files.filter is not a function
    at ng-file-select.ts:41
    at SafeSubscriber.schedulerFn [as _next] (async.js:103)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:77)
    at XMLHttpRequest.xhr.onreadystatechange (ng2-uploader.ts:103)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (zone.js:889)
    at ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:260)
    at ZoneDelegate.invokeTask (zone.js:274)
    at Zone.runTask (zone.js:151)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:345)
ErrorHandler.handleError @ error_handler.js:56
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
ng-file-select.ts:41 Uncaught TypeError: _this.files.filter is not a function
    at ng-file-select.ts:41
    at SafeSubscriber.schedulerFn [as _next] (async.js:103)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:77)
    at XMLHttpRequest.xhr.onreadystatechange (ng2-uploader.ts:103)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (zone.js:889)
    at ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:260)
    at ZoneDelegate.invokeTask (zone.js:274)
    at Zone.runTask (zone.js:151)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:345)`

### PR DESCRIPTION
**Pull request by Eikc**
As it returns a FileList instead of an array, instead i made use of the prototype.filter.call, which works perfectly in this situation where you use both the dropzone and the file input type :) 

fixes #164

### CODE REVIEW

File: src/directives/ng-file-drop.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export class NgFileDropDirective implements OnChanges, OnInit {
     this.uploader._emitter.subscribe((data: any) => {
       this.onUpload.emit(data);
       if (data.done && this.files && this.files.length) {
-        this.files = this.files.filter(f => f.name !== data.originalName);
+        this.files = Array.prototype.filter.call(this.files, (x: any) => x.name !== data.originalName)
```
Comment (jkuri) [inline src/directives/ng-file-drop.ts]: okay, here's the catch. can you please update to `[].filter.call..` and bump version in `package.json` so I can publish it to npm. Thanks.

**Comment by jkuri** [comment]
Thanks, merging..

**Comment by Eikc** [comment]
There you go mate :)
